<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1">
<context>
    <name>ClipMonitor</name>
    <message>
        <location filename="clipmonitor.cpp" line="99"/>
        <location filename="clipmonitor.cpp" line="194"/>
        <source>Generated by QSvgGenerator</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="clipmonitor.cpp" line="100"/>
        <source>Image imported from clipboard</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="clipmonitor.cpp" line="119"/>
        <source>Save directory does not exist</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="clipmonitor.cpp" line="195"/>
        <source>HTML imported from clipboard</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="Main.qml" line="14"/>
        <source>Image from Clipboard</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="79"/>
        <source>Capture failed</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="80"/>
        <source>Could not capture image</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="84"/>
        <source>Image captured</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="85"/>
        <location filename="Main.qml" line="87"/>
        <source>Saved file %1</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="129"/>
        <source>Simple tool which automatically captures contents of clipboard and saves it as image</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="135"/>
        <source>Save location</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="149"/>
        <source>...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="161"/>
        <source>Save mode</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="169"/>
        <source>SVG</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="178"/>
        <source>PNG</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="187"/>
        <source>JPG</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="198"/>
        <source>Render HTML</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="204"/>
        <source>Enable HTML rendering</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="216"/>
        <source>Page width:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="233"/>
        <source>Note: This feature uses Qt rendering engine, so results may not be perfect</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="241"/>
        <source>Deactivate</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="241"/>
        <source>Activate</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="282"/>
        <source>Application uses notifications to display information about captured screenshots</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="289"/>
        <source>Request</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="297"/>
        <source>Don&apos;t ask</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>SysTray</name>
    <message>
        <location filename="systray.cpp" line="21"/>
        <source>&amp;Quit</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="systray.cpp" line="34"/>
        <source>Image capture active</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="systray.cpp" line="35"/>
        <source>Image capture not active</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
