<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="pl_PL" sourcelanguage="en_US">
<context>
    <name>ClipMonitor</name>
    <message>
        <location filename="clipmonitor.cpp" line="+85"/>
        <source>Could not load source contents</source>
        <translation>Nie można załadować zawartości</translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Could not load image</source>
        <translation>Nie można załadować obrazka</translation>
    </message>
    <message>
        <location line="+37"/>
        <location line="+68"/>
        <source>Generated by QSvgGenerator</source>
        <translation>Wygenerowane przez QSvgGenerator</translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Image imported from clipboard</source>
        <translation>Obraz zaimportowany z przeglądarki</translation>
    </message>
    <message>
        <source>Save directory does not exist</source>
        <translation type="vanished">Katalog zapisu nie istnieje</translation>
    </message>
    <message>
        <location line="+68"/>
        <source>HTML imported from clipboard</source>
        <translation>HTML zaimportowany z przeglądarki</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="Main.qml" line="+17"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+17"/>
        <source>Image from Clipboard</source>
        <translation>ImgFromClip</translation>
    </message>
    <message>
        <location line="+15"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+15"/>
        <source>Capture sequence: %1</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+11"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+11"/>
        <source>Reset</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+24"/>
        <location line="+27"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+24"/>
        <location line="+27"/>
        <source>File</source>
        <translation>Plik</translation>
    </message>
    <message>
        <location line="-24"/>
        <location line="+27"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="-24"/>
        <location line="+27"/>
        <source>&amp;About</source>
        <translation>&amp;O programie</translation>
    </message>
    <message>
        <location line="-18"/>
        <location line="+27"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="-18"/>
        <location line="+27"/>
        <source>About &amp;Qt</source>
        <translation>&amp;O Qt</translation>
    </message>
    <message>
        <location line="+9"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+9"/>
        <source>&amp;Quit</source>
        <translation>&amp;Koniec</translation>
    </message>
    <message>
        <location line="+92"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+92"/>
        <source>Capture failed</source>
        <translation>Zapis nie powiódł się</translation>
    </message>
    <message>
        <location line="+1"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+1"/>
        <source>Could not capture image</source>
        <translation>Nie można zapisać obrazka</translation>
    </message>
    <message>
        <location line="+4"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+4"/>
        <source>Image captured</source>
        <translation>Obraz zapisany</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+3"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+1"/>
        <location line="+3"/>
        <source>Saved file %1</source>
        <translation>Zapisano plik %1</translation>
    </message>
    <message>
        <location line="+19"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+19"/>
        <source>Main</source>
        <translation>Główny</translation>
    </message>
    <message>
        <location line="+3"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+3"/>
        <source>Advanced</source>
        <translation>Zaawansowane</translation>
    </message>
    <message>
        <location line="+3"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+3"/>
        <source>Image Settings</source>
        <translation>Ustawienia obrazu</translation>
    </message>
    <message>
        <location line="+115"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+115"/>
        <source>Capture running</source>
        <translation>Nagrywanie aktywne</translation>
    </message>
    <message>
        <location line="+0"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+0"/>
        <source>Capture not running</source>
        <translation>Nagrywanie nieaktywne</translation>
    </message>
    <message>
        <location line="-84"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="-84"/>
        <source>Simple tool which automatically captures contents of clipboard and saves it as image</source>
        <translation>Proste narzędzie, które autmatycznie zapisuje zawartość schowka jako obrazek</translation>
    </message>
    <message>
        <location line="+6"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+6"/>
        <source>Save location</source>
        <translation>Miejsce zapisu</translation>
    </message>
    <message>
        <location line="+15"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+15"/>
        <source>...</source>
        <translation>...</translation>
    </message>
    <message>
        <location line="+12"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+12"/>
        <source>Save mode</source>
        <translation>Tryb zapisu</translation>
    </message>
    <message>
        <location line="+8"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+8"/>
        <source>SVG</source>
        <translation>SVG</translation>
    </message>
    <message>
        <location line="+9"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+9"/>
        <source>PNG</source>
        <translation>PNG</translation>
    </message>
    <message>
        <location line="+9"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+9"/>
        <source>JPG</source>
        <translation>JPG</translation>
    </message>
    <message>
        <location line="+76"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+76"/>
        <source>Render HTML</source>
        <translation>Rysuj HTML</translation>
    </message>
    <message>
        <location line="+6"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+6"/>
        <source>Enable HTML rendering</source>
        <translation>Włącz renderowanie HTML</translation>
    </message>
    <message>
        <location line="+12"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+12"/>
        <source>Page width:</source>
        <translation>Szerokość strony:</translation>
    </message>
    <message>
        <location line="+17"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+17"/>
        <source>Note: This feature uses QTextDocument rendering engine, so results may not be perfect</source>
        <translation>Uwaga: Do renderowania tekstu używany jest silnik QTextDocument, więc rezultat nie zawsze musi być zgodny z oczekiwanym</translation>
    </message>
    <message>
        <source>Note: This feature uses Qt rendering engine, so results may not be perfect</source>
        <translation type="obsolete">Uwaga: Do renderowania tekstu używany jest silnik Qt, więc rezultat nie zawsze musi być zgodny z oczekiwanym</translation>
    </message>
    <message>
        <location line="-75"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="-75"/>
        <source>Deactivate</source>
        <translation>Deaktywuj</translation>
    </message>
    <message>
        <location line="+0"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+0"/>
        <source>Activate</source>
        <translation>Aktywuj</translation>
    </message>
    <message>
        <location line="+83"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+83"/>
        <source>Name formatting</source>
        <translation>Format nazwy pliku</translation>
    </message>
    <message>
        <location line="+11"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+11"/>
        <source>Please specify how the file name is formatted
Use the following definitions:
&lt;ul&gt;
&lt;li&gt;{timestamp} - Current POSIX timestamp&lt;/li&gt;
&lt;li&gt;{date} - Current date&lt;/li&gt;
&lt;li&gt;{time} - Current time&lt;/li&gt;
&lt;li&gt;{cpu} - CPU architecture&lt;/li&gt;
&lt;li&gt;{hostname} - Name of the host&lt;/li&gt;
&lt;li&gt;{rand} - Random number&lt;/li&gt;
&lt;li&gt;{seq} - Sequence index&lt;/li&gt;
&lt;/ul&gt;</source>
        <translation>Zdefiniuj jak mają być formatowane nazwy pliku.
Dostępne modyfikatory:
&lt;ul&gt;
&lt;li&gt;{timestamp} - Aktualny znacznik czasu POSIX&lt;/li&gt;
&lt;li&gt;{date} - Aktualna data&lt;/li&gt;
&lt;li&gt;{time} - Aktyalny czas&lt;/li&gt;
&lt;li&gt;{cpu} - Architektura procesora/li&gt;
&lt;li&gt;{hostname} - Nazwa komputera&lt;/li&gt;
&lt;li&gt;{rand} - Liczba losowa&lt;/li&gt;
&lt;li&gt;{seq} - Indeks sekwencji&lt;/li&gt;
&lt;/ul&gt;</translation>
    </message>
    <message>
        <location line="+24"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+24"/>
        <source>Current format example:</source>
        <translation>Przykładowy wynik:</translation>
    </message>
    <message>
        <location line="+48"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+48"/>
        <source>Application uses notifications to display information about captured screenshots</source>
        <translation>Aplikacja używa powiadomień żeby wyświetlać informacje o zapisanych zrzutach</translation>
    </message>
    <message>
        <location line="+7"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+7"/>
        <source>Request</source>
        <translation>Zezwól</translation>
    </message>
    <message>
        <location line="+8"/>
        <location filename="../img_from_clip_build/img_from_clip/Main.qml" line="+8"/>
        <source>Don&apos;t ask</source>
        <translation type="unfinished">Nie pytaj</translation>
    </message>
</context>
<context>
    <name>StorePreferences</name>
    <message>
        <location filename="StorePreferences.qml" line="+30"/>
        <location filename="../img_from_clip_build/img_from_clip/StorePreferences.qml" line="+30"/>
        <source>PNG scale</source>
        <translation>Skalowanie PNG</translation>
    </message>
    <message>
        <location line="+10"/>
        <location filename="../img_from_clip_build/img_from_clip/StorePreferences.qml" line="+10"/>
        <source>Select at which scales PNG files should be saved. This is useful e.g. when exporting images for iOS</source>
        <translation>Wybierz w jakich dodatkowych skalach będą zapisywane obrazki PNG. Przydaje się to np. przy eksporcie obrazków dla urządzeń mobilnych</translation>
    </message>
    <message>
        <location line="+6"/>
        <location filename="../img_from_clip_build/img_from_clip/StorePreferences.qml" line="+6"/>
        <source>1.5x</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+7"/>
        <location filename="../img_from_clip_build/img_from_clip/StorePreferences.qml" line="+7"/>
        <source>2x</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+7"/>
        <location filename="../img_from_clip_build/img_from_clip/StorePreferences.qml" line="+7"/>
        <source>3x</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+7"/>
        <location filename="../img_from_clip_build/img_from_clip/StorePreferences.qml" line="+7"/>
        <source>4x</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>SysTray</name>
    <message>
        <location filename="systray.cpp" line="+22"/>
        <source>&amp;Quit</source>
        <translation>&amp;Koniec</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Image capture active</source>
        <translation>Zapis obrazków aktywny</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Image capture not active</source>
        <translation>Zapis obrazków nieaktywny</translation>
    </message>
    <message>
        <location line="+27"/>
        <source>ImgFromClip</source>
        <translation>ImgFromClip</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>ImgFromClip allows user to capture image or SVG copied into clipboard and capture it into specific location on disk automatically.&lt;br/&gt;Application icon:&lt;br/&gt;&lt;a href=&quot;https://www.flaticon.com/free-icons/screenshot&quot; title=&quot;screenshot icons&quot;&gt;Screenshot icons created by icon_small - Flaticon&lt;/a&gt;</source>
        <translation type="unfinished">ImgFromClip umożliwia użytkownikowi przechwycenie obrazu lub pliku SVG skopiowanego do schowka i automatyczne zapisanie go w określonym miejscu na dysku. &lt;br/&gt;Application icon:&lt;br/&gt;&lt;a href=&quot;https://www.flaticon.com/free-icons/screenshot&quot; title=&quot;screenshot icons&quot;&gt;Screenshot icons created by icon_small - Flaticon&lt;/a&gt;&lt;br/&gt;Strona: &lt;a href=&quot;https://github.com/jareksoft/img_from_clip&quot;&gt;https://github.com/jareksoft/img_from_clip&lt;/a&gt;</translation>
    </message>
</context>
</TS>
