<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="en_US">
<context>
    <name>ClipMonitor</name>
    <message>
        <location filename="clipmonitor.cpp" line="+83"/>
        <source>Could not load source contents</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+16"/>
        <source>Could not load image</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+37"/>
        <location line="+68"/>
        <source>Generated by QSvgGenerator</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="-67"/>
        <source>Image imported from clipboard</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+68"/>
        <source>HTML imported from clipboard</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="Main.qml" line="+15"/>
        <source>Image from Clipboard</source>
        <translation>ImgFromClip</translation>
    </message>
    <message>
        <location line="+15"/>
        <source>Capture sequence: %1</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+11"/>
        <source>Reset</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+24"/>
        <location line="+27"/>
        <source>File</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="-24"/>
        <location line="+27"/>
        <source>&amp;About</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="-18"/>
        <location line="+27"/>
        <source>About &amp;Qt</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+9"/>
        <source>&amp;Quit</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+92"/>
        <source>Capture failed</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Could not capture image</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+4"/>
        <source>Image captured</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+3"/>
        <source>Saved file %1</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+19"/>
        <source>Main</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+3"/>
        <source>Advanced</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+3"/>
        <source>Image Settings</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+115"/>
        <source>Capture running</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Capture not running</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="-84"/>
        <source>Simple tool which automatically captures contents of clipboard and saves it as image</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Save location</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+15"/>
        <source>...</source>
        <translation>...</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Save mode</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+8"/>
        <source>SVG</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+9"/>
        <source>PNG</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+9"/>
        <source>JPG</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+76"/>
        <source>Render HTML</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+6"/>
        <source>Enable HTML rendering</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Page width:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Note: This feature uses QTextDocument rendering engine, so results may not be perfect</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="-75"/>
        <source>Deactivate</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+0"/>
        <source>Activate</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+83"/>
        <source>Name formatting</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+11"/>
        <source>Please specify how the file name is formatted
Use the following definitions:
&lt;ul&gt;
&lt;li&gt;{timestamp} - Current POSIX timestamp&lt;/li&gt;
&lt;li&gt;{date} - Current date&lt;/li&gt;
&lt;li&gt;{time} - Current time&lt;/li&gt;
&lt;li&gt;{cpu} - CPU architecture&lt;/li&gt;
&lt;li&gt;{hostname} - Name of the host&lt;/li&gt;
&lt;li&gt;{rand} - Random number&lt;/li&gt;
&lt;li&gt;{seq} - Sequence index&lt;/li&gt;
&lt;/ul&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+24"/>
        <source>Current format example:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+48"/>
        <source>Application uses notifications to display information about captured screenshots</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+7"/>
        <source>Request</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+8"/>
        <source>Don&apos;t ask</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>StorePreferences</name>
    <message>
        <location filename="StorePreferences.qml" line="+27"/>
        <source>PNG scale</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+10"/>
        <source>Select at which scales PNG files should be saved. This is useful e.g. when exporting images for iOS</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+6"/>
        <source>1.5x</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+7"/>
        <source>2x</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+7"/>
        <source>3x</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+7"/>
        <source>4x</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>SysTray</name>
    <message>
        <location filename="systray.cpp" line="+20"/>
        <source>&amp;Quit</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Image capture active</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Image capture not active</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+27"/>
        <source>ImgFromClip</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+1"/>
        <source>ImgFromClip allows user to capture image or SVG copied into clipboard and capture it into specific location on disk automatically.&lt;br/&gt;Application icon:&lt;br/&gt;&lt;a href=&quot;https://www.flaticon.com/free-icons/screenshot&quot; title=&quot;screenshot icons&quot;&gt;Screenshot icons created by icon_small - Flaticon&lt;/a&gt;</source>
        <translation type="unfinished">ImgFromClip allows user to capture image or SVG copied into clipboard and capture it into specific location on disk automatically.&lt;br/&gt;Application icon:&lt;br/&gt;&lt;a href=&quot;https://www.flaticon.com/free-icons/screenshot&quot; title=&quot;screenshot icons&quot;&gt;Screenshot icons created by icon_small - Flaticon&lt;/a&gt;&lt;br/&gt;Website: &lt;a href=&quot;https://github.com/jareksoft/img_from_clip&quot;&gt;https://github.com/jareksoft/img_from_clip&lt;/a&gt;</translation>
    </message>
</context>
</TS>
