<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1">
<context>
    <name>ClipMonitor</name>
    <message>
        <location filename="clipmonitor.cpp" line="93"/>
        <location filename="clipmonitor.cpp" line="185"/>
        <source>Generated by QSvgGenerator</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="clipmonitor.cpp" line="94"/>
        <source>Image imported from clipboard</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="clipmonitor.cpp" line="111"/>
        <source>Save directory does not exist</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="clipmonitor.cpp" line="186"/>
        <source>HTML imported from clipboard</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="Main.qml" line="15"/>
        <location/>
        <source>Image from Clipboard</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="31"/>
        <location filename="Main.qml" line="49"/>
        <source>File</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="34"/>
        <location filename="Main.qml" line="52"/>
        <source>&amp;About</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="120"/>
        <location/>
        <source>Capture failed</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="121"/>
        <location/>
        <source>Could not capture image</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="125"/>
        <location/>
        <source>Image captured</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="126"/>
        <location filename="Main.qml" line="128"/>
        <location/>
        <source>Saved file %1</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="170"/>
        <location/>
        <source>Simple tool which automatically captures contents of clipboard and saves it as image</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="176"/>
        <location/>
        <source>Save location</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="190"/>
        <location/>
        <source>...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="202"/>
        <location/>
        <source>Save mode</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="210"/>
        <location/>
        <source>SVG</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="219"/>
        <location/>
        <source>PNG</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="228"/>
        <location/>
        <source>JPG</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="239"/>
        <location/>
        <source>Render HTML</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="245"/>
        <location/>
        <source>Enable HTML rendering</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="257"/>
        <location/>
        <source>Page width:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="274"/>
        <source>Note: This feature uses QTextDocument rendering engine, so results may not be perfect</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Note: This feature uses Qt rendering engine, so results may not be perfect</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="282"/>
        <location/>
        <source>Deactivate</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="282"/>
        <location/>
        <source>Activate</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="323"/>
        <location/>
        <source>Application uses notifications to display information about captured screenshots</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="330"/>
        <location/>
        <source>Request</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="Main.qml" line="338"/>
        <location/>
        <source>Don&apos;t ask</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>SysTray</name>
    <message>
        <location filename="systray.cpp" line="20"/>
        <source>&amp;Quit</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="systray.cpp" line="32"/>
        <source>Image capture active</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="systray.cpp" line="33"/>
        <source>Image capture not active</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="systray.cpp" line="51"/>
        <source>ImgFromClip</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="systray.cpp" line="52"/>
        <source>ImgFromClip allows user to capture image or SVG copied into clipboard and capture it into specific location on disk automatically.&lt;br/&gt;Application icon:&lt;br/&gt;&lt;a href=&quot;https://www.flaticon.com/free-icons/screenshot&quot; title=&quot;screenshot icons&quot;&gt;Screenshot icons created by icon_small - Flaticon&lt;/a&gt;</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
