<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="pl_PL" sourcelanguage="en">
<context>
    <name>ClipMonitor</name>
    <message>
        <location filename="clipmonitor.cpp" line="+93"/>
        <location line="+92"/>
        <source>Generated by QSvgGenerator</source>
        <translation>Wygenerowane przez QSvgGenerator</translation>
    </message>
    <message>
        <location line="-91"/>
        <source>Image imported from clipboard</source>
        <translation>Obraz zaimportowany z przeglądarki</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Save directory does not exist</source>
        <translation>Katalog zapisu nie istnieje</translation>
    </message>
    <message>
        <location line="+75"/>
        <source>HTML imported from clipboard</source>
        <translation>HTML zaimportowany z przeglądarki</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="Main.qml" line="+15"/>
        <location/>
        <source>Image from Clipboard</source>
        <translation>Obraz ze schowka</translation>
    </message>
    <message>
        <location line="+16"/>
        <location line="+18"/>
        <source>File</source>
        <translation>Plik</translation>
    </message>
    <message>
        <location line="-15"/>
        <location line="+18"/>
        <source>&amp;About</source>
        <translation>&amp;O programie</translation>
    </message>
    <message>
        <location line="+68"/>
        <location/>
        <source>Capture failed</source>
        <translation>Zapis nie powiódł się</translation>
    </message>
    <message>
        <location line="+1"/>
        <location/>
        <source>Could not capture image</source>
        <translation>Nie można zapisać obrazka</translation>
    </message>
    <message>
        <location line="+4"/>
        <location/>
        <source>Image captured</source>
        <translation>Obraz zapisany</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+2"/>
        <location/>
        <source>Saved file %1</source>
        <translation>Zapisano plik %1</translation>
    </message>
    <message>
        <location line="+42"/>
        <location/>
        <source>Simple tool which automatically captures contents of clipboard and saves it as image</source>
        <translation>Proste narzędzie, które autmatycznie zapisuje zawartość schowka jako obrazek</translation>
    </message>
    <message>
        <location line="+6"/>
        <location/>
        <source>Save location</source>
        <translation>Miejsce zapisu</translation>
    </message>
    <message>
        <location line="+14"/>
        <location/>
        <source>...</source>
        <translation>...</translation>
    </message>
    <message>
        <location line="+12"/>
        <location/>
        <source>Save mode</source>
        <translation>Tryb zapisu</translation>
    </message>
    <message>
        <location line="+8"/>
        <location/>
        <source>SVG</source>
        <translation>SVG</translation>
    </message>
    <message>
        <location line="+9"/>
        <location/>
        <source>PNG</source>
        <translation>PNG</translation>
    </message>
    <message>
        <location line="+9"/>
        <location/>
        <source>JPG</source>
        <translation>JPG</translation>
    </message>
    <message>
        <location line="+11"/>
        <location/>
        <source>Render HTML</source>
        <translation>Rysuj HTML</translation>
    </message>
    <message>
        <location line="+6"/>
        <location/>
        <source>Enable HTML rendering</source>
        <translation>Włącz renderowanie HTML</translation>
    </message>
    <message>
        <location line="+12"/>
        <location/>
        <source>Page width:</source>
        <translation>Szerokość strony:</translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Note: This feature uses QTextDocument rendering engine, so results may not be perfect</source>
        <translation>Uwaga: Do renderowania tekstu używany jest silnik QTextDocument, więc rezultat nie zawsze musi być zgodny z oczekiwanym</translation>
    </message>
    <message>
        <source>Note: This feature uses Qt rendering engine, so results may not be perfect</source>
        <translation>Uwaga: Do renderowania tekstu używany jest silnik Qt, więc rezultat nie zawsze musi być zgodny z oczekiwanym</translation>
    </message>
    <message>
        <location line="+8"/>
        <location/>
        <source>Deactivate</source>
        <translation>Deaktywuj</translation>
    </message>
    <message>
        <location line="+0"/>
        <location/>
        <source>Activate</source>
        <translation>Aktywuj</translation>
    </message>
    <message>
        <location line="+41"/>
        <location/>
        <source>Application uses notifications to display information about captured screenshots</source>
        <translation>Aplikacja używa powiadomień żeby wyświetlać informacje o zapisanych zrzutach</translation>
    </message>
    <message>
        <location line="+7"/>
        <location/>
        <source>Request</source>
        <translation>Zezwól</translation>
    </message>
    <message>
        <location line="+8"/>
        <location/>
        <source>Don&apos;t ask</source>
        <translation>Nie pytaj</translation>
    </message>
</context>
<context>
    <name>SysTray</name>
    <message>
        <location filename="systray.cpp" line="+20"/>
        <source>&amp;Quit</source>
        <translation>&amp;Koniec</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Image capture active</source>
        <translation>Zapis obrazków aktywny</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Image capture not active</source>
        <translation>Zapis obrazków nieaktywny</translation>
    </message>
    <message>
        <location line="+18"/>
        <source>ImgFromClip</source>
        <translation>ImgFromClip</translation>
    </message>
    <message>
        <location line="+1"/>
        <source>ImgFromClip allows user to capture image or SVG copied into clipboard and capture it into specific location on disk automatically.&lt;br/&gt;Application icon:&lt;br/&gt;&lt;a href=&quot;https://www.flaticon.com/free-icons/screenshot&quot; title=&quot;screenshot icons&quot;&gt;Screenshot icons created by icon_small - Flaticon&lt;/a&gt;</source>
        <translation>ImgFromClip umożliwia użytkownikowi przechwycenie obrazu lub pliku SVG skopiowanego do schowka i automatyczne zapisanie go w określonym miejscu na dysku. &lt;br/&gt;Application icon:&lt;br/&gt;&lt;a href=&quot;https://www.flaticon.com/free-icons/screenshot&quot; title=&quot;screenshot icons&quot;&gt;Screenshot icons created by icon_small - Flaticon&lt;/a&gt;</translation>
    </message>
</context>
</TS>
