<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="ko_KR">
<context>
    <name>ClipMonitor</name>
    <message>
        <location filename="clipmonitor.cpp" line="+110"/>
        <location line="+92"/>
        <source>Generated by QSvgGenerator</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="-91"/>
        <source>Image imported from clipboard</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+17"/>
        <source>Save directory does not exist</source>
        <translation type="unfinished">저장 폴더가 존재하지 않음</translation>
    </message>
    <message>
        <location line="+75"/>
        <source>HTML imported from clipboard</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="Main.qml" line="+15"/>
        <location/>
        <source>Image from Clipboard</source>
        <translation type="unfinished">ImgFromClip</translation>
    </message>
    <message>
        <location line="+17"/>
        <location line="+18"/>
        <location/>
        <source>File</source>
        <translation type="unfinished">파일</translation>
    </message>
    <message>
        <location line="-15"/>
        <location line="+18"/>
        <location/>
        <source>&amp;About</source>
        <translation type="unfinished">이 프로그램은...</translation>
    </message>
    <message>
        <location line="+9"/>
        <location/>
        <source>&amp;Quit</source>
        <translation type="unfinished">프로그램 종료</translation>
    </message>
    <message>
        <location line="+66"/>
        <location/>
        <source>Capture failed</source>
        <translation type="unfinished">저장 실패</translation>
    </message>
    <message>
        <location line="+1"/>
        <location/>
        <source>Could not capture image</source>
        <translation type="unfinished">이미지 저장불가</translation>
    </message>
    <message>
        <location line="+4"/>
        <location/>
        <source>Image captured</source>
        <translation type="unfinished">이미지 저장완료</translation>
    </message>
    <message>
        <location line="+1"/>
        <location line="+2"/>
        <location/>
        <source>Saved file %1</source>
        <translation type="unfinished">저장파일: %1</translation>
    </message>
    <message>
        <location line="+17"/>
        <location/>
        <source>Main</source>
        <translation type="unfinished">기본</translation>
    </message>
    <message>
        <location line="+3"/>
        <location/>
        <source>Advanced</source>
        <translation type="unfinished">고급설정</translation>
    </message>
    <message>
        <location line="+114"/>
        <location/>
        <source>Capture running</source>
        <translation type="unfinished">이미지를 저장하고 있습니다.</translation>
    </message>
    <message>
        <location line="+0"/>
        <location/>
        <source>Capture not running</source>
        <translation type="unfinished">이미지 저장이 중지되었습니다.</translation>
    </message>
    <message>
        <location line="-83"/>
        <location/>
        <source>Simple tool which automatically captures contents of clipboard and saves it as image</source>
        <translation type="unfinished">이 프로그램은 클립보드에 복사된 콘텐츠를 자동으로 이미지로 변환하여 저장해주는 툴입니다.</translation>
    </message>
    <message>
        <location line="+6"/>
        <location/>
        <source>Save location</source>
        <translation type="unfinished">저장장소</translation>
    </message>
    <message>
        <location line="+14"/>
        <location/>
        <source>...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+12"/>
        <location/>
        <source>Save mode</source>
        <translation type="unfinished">저장모드</translation>
    </message>
    <message>
        <location line="+8"/>
        <location/>
        <source>SVG</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+9"/>
        <location/>
        <source>PNG</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+9"/>
        <location/>
        <source>JPG</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+36"/>
        <location/>
        <source>Deactivate</source>
        <translation type="unfinished">중지</translation>
    </message>
    <message>
        <location line="+0"/>
        <location/>
        <source>Activate</source>
        <translation type="unfinished">시작</translation>
    </message>
    <message>
        <location line="+40"/>
        <location/>
        <source>Render HTML</source>
        <translation type="unfinished">렌더 HTML</translation>
    </message>
    <message>
        <location line="+6"/>
        <location/>
        <source>Enable HTML rendering</source>
        <translation type="unfinished">HTML 렌더링 활성화</translation>
    </message>
    <message>
        <location line="+12"/>
        <location/>
        <source>Page width:</source>
        <translation type="unfinished">이미지 가로 크기</translation>
    </message>
    <message>
        <location line="+17"/>
        <location/>
        <source>Note: This feature uses QTextDocument rendering engine, so results may not be perfect</source>
        <translation type="unfinished">노트: 이 기능은 QTextDocument 렌더링 엔진을 사용하므로 결과가 완벽하지 않을 수 있습니다.</translation>
    </message>
    <message>
        <location line="+8"/>
        <location/>
        <source>Name formatting</source>
        <translation type="unfinished">파일명 양식지정</translation>
    </message>
    <message>
        <location line="+11"/>
        <location/>
        <source>Please specify how the file name is formatted
Use the following definitions:
&lt;ul&gt;
&lt;li&gt;{timestamp} - Current POSIX timestamp&lt;/li&gt;
&lt;li&gt;{date} - Current date&lt;/li&gt;
&lt;li&gt;{time} - Current time&lt;/li&gt;
&lt;li&gt;{cpu} - CPU architecture&lt;/li&gt;
&lt;li&gt;{hostname} - Name of the host&lt;/li&gt;
&lt;li&gt;{rand} - Random number&lt;/li&gt;
&lt;li&gt;{seq} - Sequence index&lt;/li&gt;
&lt;/ul&gt;</source>
        <translation type="unfinished">파일명 양식을 지정해주세요.
다음의 정의를 따라주십시오:
&lt;ul&gt;
&lt;li&gt;{timestamp} - Current POSIX timestamp&lt;/li&gt;
&lt;li&gt;{date} - Current date&lt;/li&gt;
&lt;li&gt;{time} - Current time&lt;/li&gt;
&lt;li&gt;{cpu} - CPU architecture&lt;/li&gt;
&lt;li&gt;{hostname} - Name of the host&lt;/li&gt;
&lt;li&gt;{rand} - Random number&lt;/li&gt;
&lt;li&gt;{seq} - Sequence index&lt;/li&gt;
&lt;/ul&gt;</translation>
    </message>
    <message>
        <location line="+24"/>
        <location/>
        <source>Current format example:</source>
        <translation type="unfinished">현재 파일명 양식 예시:</translation>
    </message>
    <message>
        <location line="+44"/>
        <location/>
        <source>Application uses notifications to display information about captured screenshots</source>
        <translation type="unfinished">이 프로그램은 저장된 이미지 정보를 보여주는 알림을 사용합니다.</translation>
    </message>
    <message>
        <location line="+7"/>
        <location/>
        <source>Request</source>
        <translation type="unfinished">알림 허용</translation>
    </message>
    <message>
        <location line="+8"/>
        <location/>
        <source>Don&apos;t ask</source>
        <translation type="unfinished">다시 묻지 않음</translation>
    </message>
    <message>
        <source>Note: This feature uses Qt rendering engine, so results may not be perfect</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>SysTray</name>
    <message>
        <location filename="systray.cpp" line="+20"/>
        <source>&amp;Quit</source>
        <translation type="unfinished">프로그램 종료</translation>
    </message>
    <message>
        <location line="+12"/>
        <source>Image capture active</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+1"/>
        <source>Image capture not active</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+18"/>
        <source>ImgFromClip</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location line="+1"/>
        <source>ImgFromClip allows user to capture image or SVG copied into clipboard and capture it into specific location on disk automatically.&lt;br/&gt;Application icon:&lt;br/&gt;&lt;a href=&quot;https://www.flaticon.com/free-icons/screenshot&quot; title=&quot;screenshot icons&quot;&gt;Screenshot icons created by icon_small - Flaticon&lt;/a&gt;</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
