<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="pl_PL" sourcelanguage="en">
<context>
    <name>ClipMonitor</name>
    <message>
        <location filename="clipmonitor.cpp" line="99"/>
        <location filename="clipmonitor.cpp" line="194"/>
        <source>Generated by QSvgGenerator</source>
        <translation>Wygenerowane przez QSvgGenerator</translation>
    </message>
    <message>
        <location filename="clipmonitor.cpp" line="100"/>
        <source>Image imported from clipboard</source>
        <translation>Obraz zaimportowany z przeglądarki</translation>
    </message>
    <message>
        <location filename="clipmonitor.cpp" line="119"/>
        <source>Save directory does not exist</source>
        <translation>Katalog zapisu nie istnieje</translation>
    </message>
    <message>
        <location filename="clipmonitor.cpp" line="195"/>
        <source>HTML imported from clipboard</source>
        <translation>HTML zaimportowany z przeglądarki</translation>
    </message>
</context>
<context>
    <name>Main</name>
    <message>
        <location filename="Main.qml" line="14"/>
        <source>Image from Clipboard</source>
        <translation>Obraz ze schowka</translation>
    </message>
    <message>
        <location filename="Main.qml" line="79"/>
        <source>Capture failed</source>
        <translation>Zapis nie powiódł się</translation>
    </message>
    <message>
        <location filename="Main.qml" line="80"/>
        <source>Could not capture image</source>
        <translation>Nie można zapisać obrazka</translation>
    </message>
    <message>
        <location filename="Main.qml" line="84"/>
        <source>Image captured</source>
        <translation>Obraz zapisany</translation>
    </message>
    <message>
        <location filename="Main.qml" line="85"/>
        <location filename="Main.qml" line="87"/>
        <source>Saved file %1</source>
        <translation>Zapisano plik %1</translation>
    </message>
    <message>
        <location filename="Main.qml" line="129"/>
        <source>Simple tool which automatically captures contents of clipboard and saves it as image</source>
        <translation>Proste narzędzie, które autmatycznie zapisuje zawartość schowka jako obrazek</translation>
    </message>
    <message>
        <location filename="Main.qml" line="135"/>
        <source>Save location</source>
        <translation>Miejsce zapisu</translation>
    </message>
    <message>
        <location filename="Main.qml" line="149"/>
        <source>...</source>
        <translation>...</translation>
    </message>
    <message>
        <location filename="Main.qml" line="161"/>
        <source>Save mode</source>
        <translation>Tryb zapisu</translation>
    </message>
    <message>
        <location filename="Main.qml" line="169"/>
        <source>SVG</source>
        <translation>SVG</translation>
    </message>
    <message>
        <location filename="Main.qml" line="178"/>
        <source>PNG</source>
        <translation>PNG</translation>
    </message>
    <message>
        <location filename="Main.qml" line="187"/>
        <source>JPG</source>
        <translation>JPG</translation>
    </message>
    <message>
        <location filename="Main.qml" line="198"/>
        <source>Render HTML</source>
        <translation>Rysuj HTML</translation>
    </message>
    <message>
        <location filename="Main.qml" line="204"/>
        <source>Enable HTML rendering</source>
        <translation>Włącz renderowanie HTML</translation>
    </message>
    <message>
        <location filename="Main.qml" line="216"/>
        <source>Page width:</source>
        <translation>Szerokość strony:</translation>
    </message>
    <message>
        <location filename="Main.qml" line="233"/>
        <source>Note: This feature uses Qt rendering engine, so results may not be perfect</source>
        <translation>Uwaga: Do renderowania tekstu używany jest silnik Qt, więc rezultat nie zawsze musi być zgodny z oczekiwanym</translation>
    </message>
    <message>
        <location filename="Main.qml" line="241"/>
        <source>Deactivate</source>
        <translation>Deaktywuj</translation>
    </message>
    <message>
        <location filename="Main.qml" line="241"/>
        <source>Activate</source>
        <translation>Aktywuj</translation>
    </message>
    <message>
        <location filename="Main.qml" line="282"/>
        <source>Application uses notifications to display information about captured screenshots</source>
        <translation>Aplikacja używa powiadomień żeby wyświetlać informacje o zapisanych zrzutach</translation>
    </message>
    <message>
        <location filename="Main.qml" line="289"/>
        <source>Request</source>
        <translation>Zezwól</translation>
    </message>
    <message>
        <location filename="Main.qml" line="297"/>
        <source>Don&apos;t ask</source>
        <translation>Nie pytaj</translation>
    </message>
</context>
<context>
    <name>SysTray</name>
    <message>
        <location filename="systray.cpp" line="21"/>
        <source>&amp;Quit</source>
        <translation>&amp;Koniec</translation>
    </message>
    <message>
        <location filename="systray.cpp" line="34"/>
        <source>Image capture active</source>
        <translation>Zapis obrazków aktywny</translation>
    </message>
    <message>
        <location filename="systray.cpp" line="35"/>
        <source>Image capture not active</source>
        <translation>Zapis obrazków nieaktywny</translation>
    </message>
</context>
</TS>
