// SPDX-License-Identifier: GPL-3.0-or-later

#include "clipmonitor.h"
#include <QApplication>
#include <QBuffer>
#include <QDateTime>
#include <QDebug>
#include <QDir>
#include <QFile>
#include <QImage>
#include <QMimeData>
#include <QPainter>
#include <QRandomGenerator>
#include <QSvgGenerator>
#include <QSysInfo>
#include <QTextDocument>
#include <QTextStream>

ClipMonitor::ClipMonitor(QObject *parent) : QObject{parent} {
  m_rng.seed(static_cast<uint32_t>(QDateTime::currentMSecsSinceEpoch()));

  m_source = new ClipboardSource(this);

  QBindable<bool> activeBindable(m_source, "monitoringActive");
  activeBindable.setBinding([&]() { return m_activeBinding.value(); });

  m_source->htmlAllowedBindable().setBinding(
      [&]() { return m_htmlAllowed.value(); });

  connect(m_source, &ClipboardSource::newCapture, this,
          &ClipMonitor::newCapture, Qt::QueuedConnection);
}

auto ClipMonitor::makeNewSavePath(QString pattern) -> QString {
  if (pattern.isEmpty()) {
    pattern = QStringLiteral("{timestamp}");
  }

  pattern.replace(QStringLiteral("{timestamp}"),
                  QString::number(QDateTime::currentSecsSinceEpoch()));
  pattern.replace(QStringLiteral("{date}"),
                  QDate::currentDate().toString(Qt::DateFormat::ISODate));
  pattern.replace(QStringLiteral("{time}"),
                  QTime::currentTime().toString(Qt::DateFormat::ISODate));
  pattern.replace(QStringLiteral("{cpu}"), QSysInfo::currentCpuArchitecture());
  pattern.replace(QStringLiteral("{hostname}"), QSysInfo::machineHostName());
  pattern.replace(QStringLiteral("{rand}"), QString::number(m_rng()));

  pattern.replace(QChar('/'), QChar('_'));
  pattern.replace(QChar('\\'), QChar('_'));
  pattern.replace(QChar(':'), QChar('_'));
  pattern.replace(QChar(';'), QChar('_'));
  pattern.replace(QStringLiteral(".."), QStringLiteral("_"));

  switch (m_saveMode.value()) {
  case SaveMode::SVG:
    pattern.append(QStringLiteral(".svg"));
    break;
  case SaveMode::PNG:
    pattern.append(QStringLiteral(".png"));
    break;
  case SaveMode::JPG:
    pattern.append(QStringLiteral(".jpg"));
    break;
  }

  return pattern;
}

void ClipMonitor::saveRawSvg(const QString &contents) {
  createSave([&](QIODevice *dev) { dev->write(contents.toUtf8()); });
}

void ClipMonitor::renderSvgToPng(const QString &contents) {
  QImage image;
  if (image.loadFromData(contents.toUtf8())) {
    savePng(image);
  }
}

void ClipMonitor::renderSvgToJpg(const QString &contents) {
  QImage image;
  if (image.loadFromData(contents.toUtf8())) {
    saveJpg(image);
  }
}

void ClipMonitor::savePng(const QImage &image) {
  createSave([&](QIODevice *dev) { image.save(dev, "PNG"); });
}

void ClipMonitor::saveSvg(const QImage &image) {
  createSave([&](QIODevice *dev) {
    QSvgGenerator generator;
    QRect viewBox;
    viewBox.setSize(image.size());

    generator.setOutputDevice(dev);
    generator.setSize(image.size());
    generator.setViewBox(viewBox);
    generator.setTitle(tr("Generated by QSvgGenerator"));
    generator.setDescription(tr("Image imported from clipboard"));

    QPainter painter;
    painter.begin(&generator);
    painter.drawImage(0, 0, image);
    painter.end();
  });
}

void ClipMonitor::saveJpg(const QImage &image) {
  createSave([&](QIODevice *dev) { image.save(dev, "JPG"); });
}

void ClipMonitor::createSave(std::function<void(QIODevice *)> callback) {
  QDir dir(m_savePath.value().toLocalFile());

  if (!dir.exists()) {
    emit saveFailed(tr("Save directory does not exist"));
    return;
  }

  auto path = dir.absoluteFilePath(makeNewSavePath(m_savePattern.value()));

  QFile file(path);
  if (!file.open(QIODevice::WriteOnly | QIODevice::NewOnly)) {
    emit saveFailed(file.errorString());
    return;
  }

  qDebug() << "Saving " << file.fileName();

  callback(&file);

  if (file.error()) {
    emit saveFailed(file.errorString());
    file.remove();
  } else {
    emit notifyCapture(path);
  }
}

void ClipMonitor::newCapture(const ClipboardContents &contents) {
  // Ignore if not active
  if (!m_activeBinding.value())
    return;

  if (contents.type() == ClipboardContents::Type::Image) {
    qDebug() << "Got image";
    switch (m_saveMode) {
    case SaveMode::SVG:
      saveSvg(contents.image());
      break;
    case SaveMode::PNG:
      savePng(contents.image());
      break;
    case SaveMode::JPG:
      saveJpg(contents.image());
      break;
    }
  } else if (contents.type() == ClipboardContents::Type::Html) {
    qDebug() << "Got HTML";
    if (m_htmlAllowed.value()) {
      QTextDocument doc;
      doc.setTextWidth(m_renderWidth.value());
      doc.setHtml(contents.html());

      if (m_saveMode == SaveMode::SVG) {
        createSave([&](QIODevice *dev) {
          QSvgGenerator generator;

          QRect viewBox;
          viewBox.setSize(doc.size().toSize());

          generator.setOutputDevice(dev);
          generator.setSize(viewBox.size());
          generator.setViewBox(viewBox);
          generator.setTitle(tr("Generated by QSvgGenerator"));
          generator.setDescription(tr("HTML imported from clipboard"));

          QPainter painter;
          painter.begin(&generator);
          doc.drawContents(&painter);
          painter.end();
        });
      } else {
        QImage image(doc.size().toSize(), QImage::Format_ARGB32_Premultiplied);
        QPainter painter(&image);
        painter.setRenderHints(QPainter::Antialiasing |
                               QPainter::SmoothPixmapTransform);
        doc.drawContents(&painter);

        switch (m_saveMode) {
        case SaveMode::SVG:
          saveSvg(image);
          break;
        case SaveMode::PNG:
          savePng(image);
          break;
        case SaveMode::JPG:
          saveJpg(image);
          break;
        }
      }
    } else {
      qDebug() << "HTML not allowed";
    }
  } else if (contents.type() == ClipboardContents::Type::Text) {
    qDebug() << "Got string";
    if (!contents.text().contains(QStringLiteral("<svg")))
      return;

    switch (m_saveMode) {
    case SaveMode::SVG:
      saveRawSvg(contents.text());
      break;
    case SaveMode::PNG:
      renderSvgToPng(contents.text());
      break;
    case SaveMode::JPG:
      renderSvgToJpg(contents.text());
      break;
    }
  }
}
